[package]
name = "solutions_2025"
version = "0.1.0"
edition = "2024"

[dependencies]
common = {path = "../common"}
miette = { version = "7", features = ["fancy"] }
serde = "1.0"
serde_json = "1.0"
thiserror = "1"
